export const GET_SEARCH_REQUEST_START = 'GET_SEARCH_REQUEST_START';
export const GET_SEARCH_REQUEST_SUCCESS = 'GET_SEARCH_REQUEST_SUCCESS';
export const GET_SEARCH_REQUEST_FAIL = 'GET_SEARCH_REQUEST_FAIL';
